export interface IImmo {
  immo?: number;
  libimmo?: string;
  genre?: string;
  marque?: string;
  type?: string;
  reference?: string;
  fourn?: string;
  cpteBenef?: string;
  numBonComm?: string;
  dateBonComm?: Date | null;
  bonLiv?: string;
  dateBonLiv?: Date | null;
  numfact?: string;
  dfact?: Date | null;
  valacq?: number;
  mnttaxe?: number;
  montreeval?: number;
  valacq2?: number;
  mnttaxe2?: number;
  ddac?: Date | null;
  dms?: Date | null;
  age?: number;
  cdir?: string;
  cserv?: string;
  local?: string;
  csfam?: string;
  cptimmo?: string;
  cptamort?: string;
  cptdot?: string;
  cpttva?: string;
  taux?: number;
  duree?: number;
  dfs?: Date | null;
  amorti?: number;
  amorper?: number;
  amorti1?: number;
  valrest?: number;
  datcalc?: Date | null;
  datfam?: Date | null;
  taux2?: number;
  duree2?: number;
  dfs2?: Date | null;
  dup?: number;
  durjour?: number;
  durmois?: number;
  durjrestacour?: number;
  amortjreeval?: number;
  amortmensreeval?: number;
  nbjrecoul?: number;
  durecoul?: number;
  durjreeval?: number;
  amorti2?: number;
  amorper2?: number;
  amorti12?: number;
  valrest2?: number;
  datcalc2?: Date | null;
  datfam2?: Date | null;
  cumamort2?: number;
  cumamorttotal?: number;
  immoamort?: boolean;
  regul?: boolean;
  anccodif?: string;
  reeval?: boolean;
  fiscale?: boolean;
  contrat?: boolean;
  taxe?: boolean;
  ancCompte?: string;
  oper?: string;
  comptabilise?: string;
  item?: string;
  ImmoRattache?: number;
  numinv?: string;
  codevalo?: string;
  ancienlocal?: string;
  blocnotes?: string;
  vo_a_reev?: number;
  mnt_amorti_a_reev?: number;
  date_last_reev?: Date | null;
  num_last_reev?: number;
  coef_last_reev?: number;
  amort_jour?: number;
  vo_debut?: number;
  numSubv?: number;
  tauxSubv?: number;
  taux_impot?: number;
  taux_patente?: number;
  adPhoto?: string;
}

export const defaultValue: Readonly<IImmo> = {};
