export interface IPrepaImmo {
  numero?: number;
  libimmo?: string;
  genre?: string;
  marque?: string;
  type?: string;
  reference?: string;
  nbre?: number;
  fourn?: string;
  numfact?: string;
  numBonComm?: string;
  dateBonComm?: Date | null;
  bonLiv?: string;
  dateBonLiv?: Date | null;
  dfact?: Date | null;
  valacq?: number;
  mnttaxe?: number;
  montreeval?: number;
  valacq2?: number;
  mnttaxe2?: number;
  ddac?: Date | null;
  dms?: Date | null;
  age?: number;
  cdir?: string;
  cserv?: string;
  local?: string;
  csfam?: string;
  cpttva?: string;
  cptimmo?: string;
  cptamort?: string;
  cptdot?: string;
  taux?: number;
  taux2?: number;
  duree2?: number;
  cpteBenef?: string;
  immoamort?: boolean;
  regul?: boolean;
  reeval?: boolean;
  anccodif?: string;
  fiscale?: boolean;
  contrat?: boolean;
  taxe?: boolean;
  ancCompte?: string;
  operateurSaisi?: string;
  etat?: string;
  motifRejet?: string;
  nummodif?: number;
  item?: string;
  comptabilise?: string;
  ImmoRattache?: number;
  numinv?: string;
  codevalo?: string;
  ancienlocal?: string;
  numAvance?: number;
  blocnotes?: string;
  SSMA_TimeStamp?: Date | null;
  numSubv?: number;
  tauxSubv?: number;
}

export const defaultValue: Readonly<IPrepaImmo> = {};
